"""Generate the mechanical training-domain mapping configs from the real skills data.

Emits, under configs/training/mappings/:
  - metric_catalog.yaml   (category_defaults for each skill_category + one metric per skill)
  - benchmarks.yaml       (per-skill pass-mark default)
  - topic_map.yaml        (skill -> topic label, topic -> conversation_type)

Source of truth for the skill set is the ingested skills frame (so source_metric_key
matches the data exactly); human labels come from configs/mappings/training_profiles.yaml.
Re-runnable: overwrites the three generated files. The small files (active.yaml,
thresholds, priorities, source_catalog) are hand-authored, not generated.

    python tools/gen_training_configs.py [--skills-csv PATH] [--pass-mark 0.80]
"""
from __future__ import annotations

import argparse
from pathlib import Path

import pandas as pd
import yaml

REPO = Path(__file__).resolve().parent.parent
OUT = REPO / "configs" / "training" / "mappings"
PROFILES = REPO / "configs" / "mappings" / "training_profiles.yaml"
PROD_CATALOG = REPO / "configs" / "mappings" / "metric_catalog.yaml"


def _labelize(skill_id: str) -> str:
    return skill_id.replace("_", " ").title()


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--skills-csv", default=str(REPO / "data/raw/adhoc/latest/training_assist_skills.csv"))
    ap.add_argument("--pass-mark", type=float, default=0.80)
    args = ap.parse_args()

    df = pd.read_csv(args.skills_csv)
    # distinct (skill, category) present in the real data
    pairs = (df[["skill", "category"]].drop_duplicates()
             .sort_values(["category", "skill"]).reset_index(drop=True))

    profiles = yaml.safe_load(PROFILES.read_text(encoding="utf-8")) or {}
    skills_meta = profiles.get("skills") or {}
    cats_meta = profiles.get("skill_categories") or {}

    # reuse a known-valid base_weight_class from the production catalog (quality_behavior)
    prod = yaml.safe_load(PROD_CATALOG.read_text(encoding="utf-8")) or {}
    prod_mc = prod.get("metric_catalog", prod)
    prod_cd = (prod_mc.get("category_defaults") or {}).get("quality_behavior") or {}
    weight_class = prod_cd.get("base_weight_class", "low")

    categories = list(dict.fromkeys(pairs["category"].tolist()))

    # ---- metric_catalog.yaml ----
    category_defaults = {}
    for c in categories:
        category_defaults[c] = {
            "base_weight_class": weight_class,
            "confidence_floor": 0.30,            # day-grain: sparser evidence than weekly
            "display": {"scale": 100, "suffix": "%", "decimals": 0},
            "recalc": {"recipe": "quality"},     # skills are pass-rates -> p25 recipe
        }

    metrics = {}
    for _, row in pairs.iterrows():
        sid, cat = row["skill"], row["category"]
        label = (skills_meta.get(sid) or {}).get("label") or _labelize(sid)
        metrics[sid] = {
            "source": "training_assist_skills",
            "source_metric_key": sid,            # matches the `skill` column value exactly
            "category": cat,
            "direction": "higher_is_better",     # pass-rate: higher is better
            "unit": "score",
            "description": f"TrAIning Assist skill pass-rate: {label}.",
            "required": False,
            "eligible_for_prioritization": True,
            "computation_override": {
                "expected_calculation": "score",
                "denominator_min": 3,            # day-grain: small per-day opportunity counts
            },
            "benchmark": {"type": "config"},
        }

    metric_catalog = {"metric_catalog": {"category_defaults": category_defaults, "metrics": metrics}}

    # ---- benchmarks.yaml ----
    benchmarks = {"benchmarks": {sid: {"default": args.pass_mark} for sid in metrics}}

    # ---- topic_map.yaml ----
    metric_to_topic = {}
    topic_to_ct = {}
    for sid in metrics:
        label = (skills_meta.get(sid) or {}).get("label") or _labelize(sid)
        cat = metrics[sid]["category"]
        cat_label = (cats_meta.get(cat) or {}).get("label") or _labelize(cat)
        topic = f"Retake: {label}"          # remediation-flavored topic
        metric_to_topic[sid] = topic
        topic_to_ct[topic] = "Re-training"
    topic_map = {"topic_map": {"metric_to_topic": metric_to_topic,
                               "topic_to_conversation_type": topic_to_ct}}

    OUT.mkdir(parents=True, exist_ok=True)
    _dump(OUT / "metric_catalog.yaml", metric_catalog,
          "# GENERATED by tools/gen_training_configs.py -- training skill metrics.\n"
          "# Re-run after the skill set changes. Curate freely afterward.\n")
    _dump(OUT / "benchmarks.yaml", benchmarks,
          f"# GENERATED by tools/gen_training_configs.py -- per-skill pass-mark ({args.pass_mark:.0%}).\n")
    _dump(OUT / "topic_map.yaml", topic_map,
          "# GENERATED by tools/gen_training_configs.py -- skill -> remediation topic.\n")

    print(f"Wrote {len(metrics)} skill metrics across {len(categories)} categories to {OUT}")
    return 0


def _dump(path: Path, obj: dict, header: str) -> None:
    with path.open("w", encoding="utf-8", newline="\n") as f:
        f.write(header)
        yaml.safe_dump(obj, f, sort_keys=False, default_flow_style=False, allow_unicode=True)


if __name__ == "__main__":
    raise SystemExit(main())
